[workspace]
authors = ["VasanthakumarV <vasanth260m12@gmail.com>"]
channels = ["conda-forge"]
name = "nu_plugin_connectorx"
version = "0.1.0"
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64", "linux-aarch64"]

[tasks]
test = "cargo test"
install = "cargo install --path ."
ci-fmt = "cargo fmt --check"
ci-clippy = "cargo clippy --all-features -- -D warnings"

[dependencies]
rust = ">=1.93.1,<1.94"
rust-src = ">=1.93.1,<2"

[target.linux.dependencies]
openssl = ">=3.6.1,<4"
krb5-static = ">=1.22.2,<2"
clang = ">=22.1.0,<23"
zlib = ">=1.3.1,<2"
